/// Events generated by comparing Dota 2 game states
#[derive(Debug, Clone, PartialEq)]
pub enum GameEvent {
    /// Events related to hero abilities
    AbilityEvent(Ability),
    /// Events related to the state of the Dota 2 map
    MapEvent(Map),
    /// Events related to the player
    PlayerEvent(Player),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Ability {
    /// An ability's level went up, possibly by more than 1
    LevelledUp {
        name: String,
        level: u8,
        ultimate: bool,
    },
    /// An ability (previously active) went on cooldown
    WentOnCooldown {
        name: String,
        remaining: u16,
        ultimate: bool,
    },
    /// An ability (previously in cooldown) went off cooldown
    WentOffCooldown { name: String, ultimate: bool },
    /// An ability was activated (and it still is active)
    Activated { name: String, ultimate: bool },
    /// An ability was deactivated
    Deactivated { name: String, ultimate: bool },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Map {
    /// Daytime started
    StartedDay,
    /// Nightime started
    StartedNight { nightstalker: bool },
}

#[derive(Debug, Clone, PartialEq)]
pub enum Player {
    /// A player secured one or more kills
    ///
    /// Includes the current kill stream.
    SecuredKill {
        name: String,
        kills: u16,
        streak: u16,
    },
    /// A player died
    Died { name: String, deaths: u16 },
    /// A player got an assist
    Assisted { name: String, assists: u16 },
}
